# Form implementation generated from reading ui file 'about_us.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_About_Us(object):
    def setupUi(self, Dialog_About_Us):
        Dialog_About_Us.setObjectName("Dialog_About_Us")
        Dialog_About_Us.resize(655, 415)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        Dialog_About_Us.setFont(font)
        Dialog_About_Us.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        Dialog_About_Us.setStyleSheet("QDialog{\n"
"    background-color: rgb(250,200,200)\n"
"}")
        self.label = QtWidgets.QLabel(Dialog_About_Us)
        self.label.setGeometry(QtCore.QRect(10, 80, 641, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_about_us_label = QtWidgets.QLabel(Dialog_About_Us)
        self.label_about_us_label.setGeometry(QtCore.QRect(260, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_about_us_label.setFont(font)
        self.label_about_us_label.setStyleSheet("QLabel{\n"
"    color: red\n"
"\n"
"}")
        self.label_about_us_label.setObjectName("label_about_us_label")

        self.retranslateUi(Dialog_About_Us)
        QtCore.QMetaObject.connectSlotsByName(Dialog_About_Us)

    def retranslateUi(self, Dialog_About_Us):
        _translate = QtCore.QCoreApplication.translate
        Dialog_About_Us.setWindowTitle(_translate("Dialog_About_Us", "About Us"))
        self.label.setText(_translate("Dialog_About_Us", "This product is developed by the undergraduate final year student named \n"
"Anthonio Ekwe under the supervision Mr. Kufreh Sampson at University of \nHertfordshire, "
"United Kingdom. \n"
" This is capstone project which is related to the field of cybersecurity. \n"
"We are team of three members working on this project.\n"
" Our third team member is the second marker of this project. \n"
" For further details, you can contact us at the following email.\n"
" ae20abo@herts.ac.uk"))
        self.label_about_us_label.setText(_translate("Dialog_About_Us", "About Us"))


