# Form implementation generated from reading ui file 'addRule.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
#from script.script import append_new_rule
import subprocess
import ipaddress
import os

class add_rule_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 426)
        self.tabWidget_rules = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget_rules.setGeometry(QtCore.QRect(10, 20, 631, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tabWidget_rules.sizePolicy().hasHeightForWidth())
        self.tabWidget_rules.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.tabWidget_rules.setFont(font)
        self.tabWidget_rules.setStyleSheet("QTabWidget{\n"
                                           "    background-color:rgb(144, 238, 144)\n"
                                           "}")
        self.tabWidget_rules.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget_rules.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget_rules.setObjectName("tabWidget_rules")
        self.tab_view_rules = QtWidgets.QWidget()
        self.tab_view_rules.setObjectName("tab_view_rules")
        self.tabWidget_rules.addTab(self.tab_view_rules, "")
        self.tab_add_rule = QtWidgets.QWidget()
        self.tab_add_rule.setObjectName("tab_add_rule")
        self.widget = QtWidgets.QWidget(parent=self.tab_add_rule)
        self.widget.setGeometry(QtCore.QRect(10, 10, 111, 161))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widget1 = QtWidgets.QWidget(parent=self.tab_add_rule)
        self.widget1.setGeometry(QtCore.QRect(290, 20, 320, 34))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_ipaddress = QtWidgets.QLineEdit(parent=self.widget1)
        self.lineEdit_ipaddress.setObjectName("lineEdit_ipaddress")
        self.horizontalLayout.addWidget(self.lineEdit_ipaddress)
        self.widget2 = QtWidgets.QWidget(parent=self.tab_add_rule)
        self.widget2.setGeometry(QtCore.QRect(320, 80, 281, 34))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_port = QtWidgets.QLineEdit(parent=self.widget2)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.widget3 = QtWidgets.QWidget(parent=self.tab_add_rule)
        self.widget3.setGeometry(QtCore.QRect(310, 140, 162, 34))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.widget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_action_type = QtWidgets.QComboBox(parent=self.widget3)
        self.comboBox_action_type.setObjectName("comboBox_action_type")
        self.comboBox_action_type.addItem("")
        self.comboBox_action_type.addItem("")
        self.comboBox_action_type.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_action_type)
        self.widget4 = QtWidgets.QWidget(parent=self.tab_add_rule)
        self.widget4.setGeometry(QtCore.QRect(140, 10, 101, 171))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_table = QtWidgets.QComboBox(parent=self.widget4)
        self.comboBox_table.setObjectName("comboBox_table")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_table)
        self.comboBox_chain = QtWidgets.QComboBox(parent=self.widget4)
        self.comboBox_chain.setObjectName("comboBox_chain")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_chain)
        self.comboBox_traffic_type = QtWidgets.QComboBox(parent=self.widget4)
        self.comboBox_traffic_type.setObjectName("comboBox_traffic_type")
        self.comboBox_traffic_type.addItem("")
        self.comboBox_traffic_type.addItem("")
        self.comboBox_traffic_type.addItem("")
        self.comboBox_traffic_type.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_traffic_type)
        self.widget5 = QtWidgets.QWidget(parent=self.tab_add_rule)
        self.widget5.setGeometry(QtCore.QRect(10, 190, 591, 151))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.widget5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_webAddress = QtWidgets.QLineEdit(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_webAddress.setFont(font)
        self.lineEdit_webAddress.setObjectName("lineEdit_webAddress")
        self.horizontalLayout_4.addWidget(self.lineEdit_webAddress)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pushButton_add_rule = QtWidgets.QPushButton(parent=self.widget5)
        self.pushButton_add_rule.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_rule.sizePolicy().hasHeightForWidth())
        self.pushButton_add_rule.setSizePolicy(sizePolicy)
        self.pushButton_add_rule.setMaximumSize(QtCore.QSize(145, 16777215))
        self.pushButton_add_rule.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_add_rule.setAutoDefault(False)
        self.pushButton_add_rule.setDefault(True)
        self.pushButton_add_rule.setObjectName("pushButton_add_rule")
        self.pushButton_add_rule.clicked.connect(self.add_rule_to_script)
        self.verticalLayout_3.addWidget(self.pushButton_add_rule)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.label_add_rule_msg = QtWidgets.QLabel(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_add_rule_msg.setFont(font)
        self.label_add_rule_msg.setObjectName("label_add_rule_msg")


        self.verticalLayout_4.addWidget(self.label_add_rule_msg)
        self.tabWidget_rules.addTab(self.tab_add_rule, "")
        self.tab_delete_rule = QtWidgets.QWidget()
        self.tab_delete_rule.setObjectName("tab_delete_rule")
        self.tabWidget_rules.addTab(self.tab_delete_rule, "")

        self.retranslateUi(Dialog)
        self.tabWidget_rules.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def validate_ip_address(self,ip_string):
        try:
            ip_object = ipaddress.ip_address(ip_string)
            return True
        except ValueError:
            return False

    def add_rule_to_script(self):
        table = self.comboBox_table.itemText(self.comboBox_table.currentIndex())
        chain = self.comboBox_chain.itemText(self.comboBox_chain.currentIndex())
        traffic_type = self.comboBox_traffic_type.itemText(self.comboBox_traffic_type.currentIndex())
        action_type = self.comboBox_action_type.itemText(self.comboBox_action_type.currentIndex())
        website = self.lineEdit_webAddress.text()
        ip_address = self.lineEdit_ipaddress.text()
        port = self.lineEdit_port.text()
        port_validity= False
        ipValidity = False
        msg=""
        if port != "":
            if int(port) <= 1 or int(port) >65535 :
                msg= msg+ f"Port '{port}' is invalid. "
            else:
                port_validity = True

        if ip_address!="":
                ip_validity = self.validate_ip_address(ip_address)
                if ip_validity == False:
                    msg = msg + f"The IP address '{ip_address}' is not valid"
                    self.label_add_rule_msg.setText(msg)
                else:
                    ipValidity == True
        if msg!="":
            self.label_add_rule_msg.setText(msg)
        else:
            self.label_add_rule_msg.setText("")

        Query = ""
        if table=="None" or table == "FILTER":
            Query = "iptables -t filter"
        else :
            Query="iptables -t "+ table
        if chain!="None":
            Query = Query + " -A " + chain
        if traffic_type!="None":
            Query = Query + " -p " + traffic_type
        if port_validity == True:
            Query = Query + " --dport " + port
        if ipaddress!="" and self.validate_ip_address(ip_address)==True:
            Query = Query + " -s " + ip_address

        if website!='':
            Query = Query + " -d " + website
        if action_type!='None':
            Query = Query + " -j " + action_type

        self.label_add_rule_msg.setText(Query)
        self.lineEdit_ipaddress.setText("")
        self.lineEdit_webAddress.setText("")
        self.lineEdit_port.setText("")
        self.append_new_rule(Query)

    def append_new_rule(self,new_rule):
        with open('firewall.sh', 'a') as rsh:
            rsh.write("\n"+new_rule)
            #self.label_add_rule_msg.setText("Rule Added to the Firewall. ")
        try:
            subprocess.call(['bash','firewall.sh'])
            return True
        except ValueError:
            return False


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget_rules.setTabText(self.tabWidget_rules.indexOf(self.tab_view_rules), _translate("Dialog", "View Rules"))
        self.label.setText(_translate("Dialog", "Select Table"))
        self.label_2.setText(_translate("Dialog", "Select Chain"))
        self.label_5.setText(_translate("Dialog", "Traffic Type"))
        self.label_3.setText(_translate("Dialog", "Ip Address"))
        self.lineEdit_ipaddress.setPlaceholderText(_translate("Dialog", "Enter ip address"))
        self.label_4.setText(_translate("Dialog", "Port #"))
        self.lineEdit_port.setPlaceholderText(_translate("Dialog", "Enter Port Number"))
        self.label_6.setText(_translate("Dialog", "Action"))

        self.comboBox_action_type.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_action_type.setItemText(1, _translate("Dialog", "ACCEPT"))
        self.comboBox_action_type.setItemText(2, _translate("Dialog", "DROP"))
        self.comboBox_table.setItemText(0, _translate("Dialog", "FILTER"))
        self.comboBox_table.setItemText(1, _translate("Dialog", "NAT"))
        self.comboBox_table.setItemText(2, _translate("Dialog", "MANGLE"))
        self.comboBox_table.setItemText(3, _translate("Dialog", "RAW"))
        self.comboBox_table.setItemText(4, _translate("Dialog", "None"))
        self.comboBox_chain.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_chain.setItemText(1, _translate("Dialog", "INPUT"))
        self.comboBox_chain.setItemText(2, _translate("Dialog", "OUTPUT"))
        self.comboBox_chain.setItemText(3, _translate("Dialog", "FORWARD"))
        self.comboBox_chain.setItemText(4, _translate("Dialog", "PREROUTE"))
        self.comboBox_chain.setItemText(5, _translate("Dialog", "POSTROUTE"))

        self.comboBox_traffic_type.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_traffic_type.setItemText(1, _translate("Dialog", "TCP"))
        self.comboBox_traffic_type.setItemText(2, _translate("Dialog", "ICMP"))
        self.comboBox_traffic_type.setItemText(3, _translate("Dialog", "UDP"))
        self.label_7.setText(_translate("Dialog", "Website Adress"))
        self.lineEdit_webAddress.setPlaceholderText(_translate("Dialog", "Enter website address "))
        self.pushButton_add_rule.setText(_translate("Dialog", "Add Rule"))
        self.label_add_rule_msg.setText(_translate("Dialog", "Message:"))
        self.tabWidget_rules.setTabText(self.tabWidget_rules.indexOf(self.tab_add_rule), _translate("Dialog", "Add Rule"))
        self.tabWidget_rules.setTabText(self.tabWidget_rules.indexOf(self.tab_delete_rule), _translate("Dialog", "Delete Rule"))



