# Form implementation generated from reading ui file 'addRule2.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem
import subprocess
import ipaddress
from linkedlist import LinkedList

class add_rule_Dialog(object):
    llist = LinkedList()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 426)
        self.tabWidget_rules = QtWidgets.QTabWidget(Dialog)
        self.tabWidget_rules.setGeometry(QtCore.QRect(10, 20, 631, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tabWidget_rules.sizePolicy().hasHeightForWidth())
        self.tabWidget_rules.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.tabWidget_rules.setFont(font)
        self.tabWidget_rules.setStyleSheet("QTabWidget{\n"
"    background-color:rgb(144, 238, 144)\n"
"}")
        self.tabWidget_rules.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget_rules.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget_rules.setObjectName("tabWidget_rules")
        self.tab_view_rules = QtWidgets.QWidget()
        self.tab_view_rules.setObjectName("tab_view_rules")
        self.tableWidget_view_rules = QtWidgets.QTableWidget(self.tab_view_rules)
        self.tableWidget_view_rules.setGeometry(QtCore.QRect(10, 40, 611, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.tableWidget_view_rules.setFont(font)
        self.tableWidget_view_rules.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.tableWidget_view_rules.setStyleSheet("QTableWidget{\n"
"    background-color:rgb(255, 182, 193)\n"
"\n"
"}")
        self.tableWidget_view_rules.setObjectName("tableWidget_view_rules")
        self.tableWidget_view_rules.setColumnCount(8)
        self.tableWidget_view_rules.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_view_rules.setHorizontalHeaderItem(7, item)
        self.widget = QtWidgets.QWidget(self.tab_view_rules)
        self.widget.setGeometry(QtCore.QRect(160, 0, 231, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_select_chain_view_rule = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_select_chain_view_rule.setFont(font)
        self.label_select_chain_view_rule.setObjectName("label_select_chain_view_rule")
        self.horizontalLayout_8.addWidget(self.label_select_chain_view_rule)
        self.comboBox_view_rule_chain = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_view_rule_chain.setFont(font)
        self.comboBox_view_rule_chain.setObjectName("comboBox_view_rule_chain")
        self.comboBox_view_rule_chain.addItem("")
        self.comboBox_view_rule_chain.addItem("")
        self.comboBox_view_rule_chain.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_view_rule_chain)
        self.pushButton_view_all_rules = QtWidgets.QPushButton(self.tab_view_rules)
        self.pushButton_view_all_rules.setGeometry(QtCore.QRect(470, 1, 111, 31))
        self.pushButton_view_all_rules.setObjectName("pushButton_view_all_rules")

        #connect signal
        self.pushButton_view_all_rules.clicked.connect(self.view_rules)

        self.tabWidget_rules.addTab(self.tab_view_rules, "")
        self.tab_add_rule = QtWidgets.QWidget()
        self.tab_add_rule.setObjectName("tab_add_rule")
        self.layoutWidget = QtWidgets.QWidget(self.tab_add_rule)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 20, 320, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_ipaddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ipaddress.setObjectName("lineEdit_ipaddress")
        self.horizontalLayout.addWidget(self.lineEdit_ipaddress)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_add_rule)
        self.layoutWidget1.setGeometry(QtCore.QRect(290, 80, 171, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_port = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_add_rule)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 130, 231, 34))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_action_type = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_action_type.setObjectName("comboBox_action_type")
        self.comboBox_action_type.addItem("")
        self.comboBox_action_type.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_action_type)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_add_rule)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 190, 591, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_webAddress = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_webAddress.setFont(font)
        self.lineEdit_webAddress.setObjectName("lineEdit_webAddress")
        self.horizontalLayout_4.addWidget(self.lineEdit_webAddress)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pushButton_add_rule = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_add_rule.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_rule.sizePolicy().hasHeightForWidth())
        self.pushButton_add_rule.setSizePolicy(sizePolicy)
        self.pushButton_add_rule.setMaximumSize(QtCore.QSize(145, 16777215))
        self.pushButton_add_rule.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_add_rule.setStyleSheet("QPushButton{\n"
"    background-color:rgb(218, 218, 218)\n"
"    \n"
"}")
        self.pushButton_add_rule.setAutoDefault(False)
        self.pushButton_add_rule.setDefault(True)
        self.pushButton_add_rule.setObjectName("pushButton_add_rule")

        #connect signal
        self.pushButton_add_rule.clicked.connect(self.add_rule_to_script)

        self.verticalLayout_3.addWidget(self.pushButton_add_rule)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.label_add_rule_msg = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_add_rule_msg.setFont(font)
        self.label_add_rule_msg.setObjectName("label_add_rule_msg")
        self.verticalLayout_4.addWidget(self.label_add_rule_msg)
        self.widget1 = QtWidgets.QWidget(self.tab_add_rule)
        self.widget1.setGeometry(QtCore.QRect(20, 70, 211, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_chain = QtWidgets.QComboBox(self.widget1)
        self.comboBox_chain.setObjectName("comboBox_chain")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.comboBox_chain.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_chain)
        self.widget2 = QtWidgets.QWidget(self.tab_add_rule)
        self.widget2.setGeometry(QtCore.QRect(20, 13, 211, 31))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_table = QtWidgets.QComboBox(self.widget2)
        self.comboBox_table.setObjectName("comboBox_table")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.comboBox_table.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_table)
        self.widget3 = QtWidgets.QWidget(self.tab_add_rule)
        self.widget3.setGeometry(QtCore.QRect(20, 130, 211, 31))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.comboBox_traffic_type = QtWidgets.QComboBox(self.widget3)
        self.comboBox_traffic_type.setObjectName("comboBox_traffic_type")
        self.comboBox_traffic_type.addItem("")
        self.comboBox_traffic_type.addItem("")
        self.comboBox_traffic_type.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_traffic_type)
        self.tabWidget_rules.addTab(self.tab_add_rule, "")
        self.tab_delete_rule = QtWidgets.QWidget()
        self.tab_delete_rule.setObjectName("tab_delete_rule")
        self.label_delete_rule_msg = QtWidgets.QLabel(self.tab_delete_rule)
        self.label_delete_rule_msg.setGeometry(QtCore.QRect(30, 270, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_delete_rule_msg.setFont(font)
        self.label_delete_rule_msg.setObjectName("label_delete_rule_msg")
        self.widget4 = QtWidgets.QWidget(self.tab_delete_rule)
        self.widget4.setGeometry(QtCore.QRect(160, 40, 311, 211))
        self.widget4.setObjectName("widget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.comboBox_delete_rule_chain = QtWidgets.QComboBox(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_delete_rule_chain.setFont(font)
        self.comboBox_delete_rule_chain.setObjectName("comboBox_delete_rule_chain")
        self.comboBox_delete_rule_chain.addItem("")
        self.comboBox_delete_rule_chain.addItem("")
        self.comboBox_delete_rule_chain.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_delete_rule_chain)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_enter_rule_number = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_enter_rule_number.setFont(font)
        self.label_enter_rule_number.setObjectName("label_enter_rule_number")
        self.horizontalLayout_10.addWidget(self.label_enter_rule_number)
        self.lineEdit_del_rule_no = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_del_rule_no.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_del_rule_no.setFont(font)
        self.lineEdit_del_rule_no.setObjectName("lineEdit_del_rule_no")
        self.horizontalLayout_10.addWidget(self.lineEdit_del_rule_no)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.pushButton_delete_rule = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_delete_rule.setFont(font)
        self.pushButton_delete_rule.setStyleSheet("QPushButton{\n"
"    background-color:rgb(250,0,0)\n"
"\n"
"}")
        self.pushButton_delete_rule.setObjectName("pushButton_delete_rule")
        self.verticalLayout.addWidget(self.pushButton_delete_rule)
        self.tabWidget_rules.addTab(self.tab_delete_rule, "")

        self.retranslateUi(Dialog)
        self.tabWidget_rules.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def validate_ip_address(self,ip_string):
        try:
            ip_object = ipaddress.ip_address(ip_string)
            return True
        except ValueError:
            return False

    def add_rule_to_script(self):
        table = self.comboBox_table.itemText(self.comboBox_table.currentIndex())
        chain = self.comboBox_chain.itemText(self.comboBox_chain.currentIndex())
        traffic_type = self.comboBox_traffic_type.itemText(self.comboBox_traffic_type.currentIndex())
        action_type = self.comboBox_action_type.itemText(self.comboBox_action_type.currentIndex())
        website = self.lineEdit_webAddress.text()
        ip_address = self.lineEdit_ipaddress.text()
        port = self.lineEdit_port.text()
        port_validity= False
        ipValidity = False
        msg=""
        if port != "":
            if int(port) <= 1 or int(port) >65535 :
                msg= msg+ f"Port '{port}' is invalid. "
            else:
                port_validity = True

        if ip_address!="":
                ip_validity = self.validate_ip_address(ip_address)
                if ip_validity == False:
                    msg = msg + f"The IP address '{ip_address}' is not valid"
                    self.label_add_rule_msg.setText(msg)
                else:
                    ipValidity == True
        if msg!="":
            self.label_add_rule_msg.setText(msg)
        else:
            self.label_add_rule_msg.setText("")

        Query = ""
        if table=="None" or table == "FILTER":
            Query = "iptables -t filter"
        else :
            Query="iptables -t "+ table
        if chain!="None":
            Query = Query + " -A " + chain
        if traffic_type!="None":
            Query = Query + " -p " + traffic_type
        if port_validity == True:
            Query = Query + " --dport " + port
        if ipaddress!="" and self.validate_ip_address(ip_address)==True:
            Query = Query + " -s " + ip_address

        if website!='':
            Query = Query + " -d " + website
        if action_type!='None':
            Query = Query + " -j " + action_type

        self.label_add_rule_msg.setText(Query)
        self.lineEdit_ipaddress.setText("")
        self.lineEdit_webAddress.setText("")
        self.lineEdit_port.setText("")

        # if llist.search(3,4,5) is not None:
        #     llist.delete(3,4,5)
        insert_data = [table,chain,traffic_type,port,ip_address,website,action_type]
        self.llist.insert(insert_data)
        with open('firewall.sh', 'w') as rsh:
            rsh.write("#! /bin/bash \n")
            rsh.write("iptables -F \n")
        self.llist.print_list()
        #self.append_new_rule(Query)
    def delete_rule(self,del_rule):
        pass
        
    def append_new_rule(self,new_rule):
        with open('firewall.sh', 'a') as rsh:
            rsh.write("\n"+new_rule)
            #self.label_add_rule_msg.setText("Rule Added to the Firewall. ")
        try:
            subprocess.call(['bash','firewall.sh'])
            return True
        except ValueError:
            return False

    def view_rules(self):
        rules = self.fetch_rules()
        # current = self.llist.head
        # rules = []
        # i=1
        # while current is not None:
        #     rules.append([str(i),current.data[0], current.data[1], current.data[2], current.data[3],current.data[5],current.data[4] , current.data[6]])
        #     current = current.next
        #     i+=1
        self.tableWidget_view_rules.setRowCount(0)
        row=0
        for rule in rules:
            self.tableWidget_view_rules.insertRow(row)
            col=0
            for r in rule:
                self.tableWidget_view_rules.setItem(row,col,QTableWidgetItem(r))
                col+=1
            row+=1


    def fetch_rules(self):
        rule = []
        with open('firewall.sh', 'r') as rsh:
            num = 1
            while (rsh):
                line = rsh.readline()
                if line == "\n":
                    continue
                if line == "":
                    break
                line = line.split()
                table = ""
                chain = ""
                port = ""
                website = ""
                ip_add = ""
                traffic = ""
                action = ""
                for e in line:

                    if e == '-t':
                        table = line[line.index(e) + 1]
                        # print(table)
                    if e == '-A':
                        chain = line[line.index(e) + 1]
                        # print(chain)
                    if e == '-p':
                        traffic = line[line.index(e) + 1]
                        # print(traffic)
                    if e == '--dport':
                        port = line[line.index(e) + 1]
                        # print(port)
                    if e == '-s':
                        ip_add = line[line.index(e) + 1]
                        # print(ip_add)
                    if e == '-j':
                        action = line[line.index(e) + 1]
                    if e == '-d':
                        website = line[line.index(e) + 1]
                        # print(action)
                if table == "" and action != "":
                    table = "filter"
                if action != "":
                    data1 = [table, chain, traffic, port,ip_add,website, action]
                    #self.llist.insert(data1)
                    rule.append([str(num-2),table, chain, traffic, port,ip_add,website, action])
                num+=1
        return rule

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Rule No."))
        item = self.tableWidget_view_rules.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Table"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Chain"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Protocol"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Port"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Website"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "IP Adress"))
        item = self.tableWidget_view_rules.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Action"))
        self.label_select_chain_view_rule.setText(_translate("Dialog", "Select Chain"))
        self.comboBox_view_rule_chain.setItemText(0, _translate("Dialog", "INPUT"))
        self.comboBox_view_rule_chain.setItemText(1, _translate("Dialog", "OUTPUT"))
        self.comboBox_view_rule_chain.setItemText(2, _translate("Dialog", "FORWARD"))
        self.pushButton_view_all_rules.setText(_translate("Dialog", "View Rules"))
        self.tabWidget_rules.setTabText(self.tabWidget_rules.indexOf(self.tab_view_rules), _translate("Dialog", "View Rules"))
        self.label_3.setText(_translate("Dialog", "Ip Address"))
        self.lineEdit_ipaddress.setPlaceholderText(_translate("Dialog", "Enter ip address"))
        self.label_4.setText(_translate("Dialog", "Port #"))
        self.lineEdit_port.setPlaceholderText(_translate("Dialog", "Enter Port Number"))
        self.label_6.setText(_translate("Dialog", "Action"))
        self.comboBox_action_type.setItemText(0, _translate("Dialog", "ACCEPT"))
        self.comboBox_action_type.setItemText(1, _translate("Dialog", "DROP"))
        self.label_7.setText(_translate("Dialog", "Website Adress"))
        self.lineEdit_webAddress.setPlaceholderText(_translate("Dialog", "Enter website address "))
        self.pushButton_add_rule.setText(_translate("Dialog", "Add Rule"))
        self.label_add_rule_msg.setText(_translate("Dialog", "Message:"))
        self.label_2.setText(_translate("Dialog", "Select Chain"))
        self.comboBox_chain.setItemText(0, _translate("Dialog", "INPUT"))
        self.comboBox_chain.setItemText(1, _translate("Dialog", "OUTPUT"))
        self.comboBox_chain.setItemText(2, _translate("Dialog", "FORWARD"))
        self.comboBox_chain.setItemText(3, _translate("Dialog", "PREROUTE"))
        self.comboBox_chain.setItemText(4, _translate("Dialog", "POSTROUTE"))
        self.label.setText(_translate("Dialog", "Select Table"))
        self.comboBox_table.setItemText(0, _translate("Dialog", "FILTER"))
        self.comboBox_table.setItemText(1, _translate("Dialog", "NAT"))
        self.comboBox_table.setItemText(2, _translate("Dialog", "MANGLE"))
        self.comboBox_table.setItemText(3, _translate("Dialog", "RAW"))
        self.label_5.setText(_translate("Dialog", "Traffic Type"))
        self.comboBox_traffic_type.setItemText(0, _translate("Dialog", "TCP"))
        self.comboBox_traffic_type.setItemText(1, _translate("Dialog", "ICMP"))
        self.comboBox_traffic_type.setItemText(2, _translate("Dialog", "UDP"))
        self.tabWidget_rules.setTabText(self.tabWidget_rules.indexOf(self.tab_add_rule), _translate("Dialog", "Add Rule"))
        self.label_delete_rule_msg.setText(_translate("Dialog", "Message:"))
        self.label_9.setText(_translate("Dialog", "Select Chain"))
        self.comboBox_delete_rule_chain.setItemText(0, _translate("Dialog", "INPUT"))
        self.comboBox_delete_rule_chain.setItemText(1, _translate("Dialog", "OUTPUT"))
        self.comboBox_delete_rule_chain.setItemText(2, _translate("Dialog", "FORWARD"))
        self.label_enter_rule_number.setText(_translate("Dialog", "Enter Rule Number"))
        self.lineEdit_del_rule_no.setPlaceholderText(_translate("Dialog", "47"))
        self.pushButton_delete_rule.setText(_translate("Dialog", "Delete Rule"))
        self.tabWidget_rules.setTabText(self.tabWidget_rules.indexOf(self.tab_delete_rule), _translate("Dialog", "Delete Rule"))



