# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_help(object):
    def setupUi(self, Dialog_help):
        Dialog_help.setObjectName("Dialog_help")
        Dialog_help.resize(655, 415)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        Dialog_help.setFont(font)
        Dialog_help.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        Dialog_help.setStyleSheet("QDialog{\n"
"    background-color: rgb(250,200,200)\n"
"}")
        self.label = QtWidgets.QLabel(Dialog_help)
        self.label.setGeometry(QtCore.QRect(10, 80, 641, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_help_label = QtWidgets.QLabel(Dialog_help)
        self.label_help_label.setGeometry(QtCore.QRect(260, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_help_label.setFont(font)
        self.label_help_label.setStyleSheet("QLabel{\n"
"    color: red\n"
"\n"
"}")
        self.label_help_label.setObjectName("label_help_label")

        self.retranslateUi(Dialog_help)
        QtCore.QMetaObject.connectSlotsByName(Dialog_help)

    def retranslateUi(self, Dialog_help):
        _translate = QtCore.QCoreApplication.translate
        Dialog_help.setWindowTitle(_translate("Dialog_help", "Help"))
        self.label.setText(_translate("Dialog_help", "For help you can email us at the following email\n"
                                                     "ae20abo@herts.ac.uk"))
        self.label_help_label.setText(_translate("Dialog_help", "Help"))


