# Form implementation generated from reading ui file 'loginForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(500, 400)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        LoginForm.setFont(font)
        LoginForm.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=LoginForm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=LoginForm)
        self.lineEdit_username.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=LoginForm)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=LoginForm)
        self.lineEdit_Password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lineEdit_Password.setTabletTracking(True)
        self.lineEdit_Password.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.horizontalLayout_2.addWidget(self.lineEdit_Password)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Login = QtWidgets.QPushButton(parent=LoginForm)
        self.pushButton_Login.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.pushButton_Login.setStyleSheet("button.setStyleSheet(\'QPushButton {background-color: #A3C1DA}\')")
        self.pushButton_Login.setObjectName("pushButton_Login")

        # connect signal
        self.pushButton_Login.clicked.connect(self.login)

        self.horizontalLayout_4.addWidget(self.pushButton_Login)
        self.pushButton_Signup = QtWidgets.QPushButton(parent=LoginForm)
        self.pushButton_Signup.setObjectName("pushButton_Signup")

        # connect signal for signUp

        self.pushButton_Signup.clicked.connect(self.signUp)

        self.horizontalLayout_4.addWidget(self.pushButton_Signup)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(parent=LoginForm)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    # def createDatabase(self):
    #     try:
    #         mydb = mc.connect(
    #             host = "localhost",
    #             user = "root",
    #             password = ""
    #         )
    #         cursor = mydb.cursor()
    #         dbname = self.lineEdit_username.text()
    #         cursor.execute("CREATE DATABASE {}".format(dbname))
    #         self.label_3.setText("Database created Successfully")
    #     except mc.Error as e:
    #         self.label_3.setText("Error")

    # def db_connect(self):
    #     try:
    #         mydb = mc.connect(
    #             host="localhost",
    #             user = "root",
    #             password = "",
    #             database = "firewall"
    #         )
    #         self.label_3.setText("Connection with database is successful")
    #     except mc.Error as e:
    #         self.label_3.setText("Error in database connection")
    def db_connect(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="anthonio",
                password="password",
                database="firewall"
            )
            return mydb

        except mc.Error as e:
            self.label_3.setText("Error in connection")
        return mydb
    def login(self):
        try:
            email = self.lineEdit_username.text()
            password = self.lineEdit_Password.text()
            mydb = self.db_connect()

            mycursor = mydb.cursor()

            query = "SELECT email, password from user where email ='" + email + "' and password like '" + password + "'"
            mycursor.execute(query)

            result = mycursor.fetchone()
            if result == None:
                self.label_3.setText(" Incorrect email or password")
            else:
                self.label_3.setText(" Congratulations!!! You are logged in. ")

            #mydb.close()


        except mc.Error as e :
            self.label_3.setStyleSheet('color:red')
            self.label_3.setText(" Error ")

    def signUp(self):
        try:
            username = self.lineEdit_username.text()
            password = self.lineEdit_Password.text()
            mydb = self.db_connect()
            mycursor = mydb.cursor()
            # query1 = "SELECT username FROM user"
            # usernames = mycursor.execute(query1)
            # print(usernames)
            usernames= []
            if username not in usernames:
                query = "INSERT INTO user (firstname,lastname,email,password) VALUES(%s,%s,%s,%s)"
                value = ("administrator","user",username,password)
                if username != "" and password !="":
                    #mycursor = mydb.cursor()
                    mycursor.execute(query,value)
                    mydb.commit()
                    self.lineEdit_username.setText("")
                    self.lineEdit_Password.setText("")
                    self.label_3.setStyleSheet('color:green')
                    self.label_3.setText("User created")
                else:

                    self.label_3.setStyleSheet('color:red')
                    self.label_3.setText("Please fill all fields")
            else:
                self.label_3.setStyleSheet('color:red')
                self.label_3.setText("This username is already taken!")

        except mc.Error as e:
            self.label_3.setText(" Error ")


    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.label.setText(_translate("LoginForm", "Username"))
        self.label_2.setText(_translate("LoginForm", "Password"))
        self.pushButton_Login.setText(_translate("LoginForm", "Login"))
        self.pushButton_Signup.setText(_translate("LoginForm", "Sign Up"))
        self.label_3.setText(_translate("LoginForm", "Database Connection Status "))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     LoginForm = QtWidgets.QWidget()
#     ui = Ui_LoginForm()
#     ui.setupUi(LoginForm)
#     LoginForm.show()
#     sys.exit(app.exec())
