# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_profile(object):
    def setupUi(self, Dialog_profile):
        Dialog_profile.setObjectName("Dialog_profile")
        Dialog_profile.resize(655, 415)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        Dialog_profile.setFont(font)
        Dialog_profile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        Dialog_profile.setStyleSheet("QDialog{\n"
"    background-color: rgb(250,200,200)\n"
"}")
        self.label = QtWidgets.QLabel(Dialog_profile)
        self.label.setGeometry(QtCore.QRect(10, 80, 641, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_profile_label = QtWidgets.QLabel(Dialog_profile)
        self.label_profile_label.setGeometry(QtCore.QRect(260, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_profile_label.setFont(font)
        self.label_profile_label.setStyleSheet("QLabel{\n"
"    color: red\n"
"\n"
"}")
        self.label_profile_label.setObjectName("label_profile_label")

        self.retranslateUi(Dialog_profile)
        QtCore.QMetaObject.connectSlotsByName(Dialog_profile)

    def retranslateUi(self, Dialog_profile):
        _translate = QtCore.QCoreApplication.translate
        Dialog_profile.setWindowTitle(_translate("Dialog_profile", "profile"))
        self.label.setText(_translate("Dialog_profile", "           First Name:        Anthoio\n\n\n"
                                                        "           Last Name :        Ekwe\n\n\n"
                                                        "           Email     :        ae20abo@herts.ac.uk"))
        self.label_profile_label.setText(_translate("Dialog_profile", "profile"))


